services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventoryDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - inventory-db-data:/var/lib/mysql
    networks:
      - ecommerce-network

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - ecommerce-network

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: krishnakant2001/discovery-service
    container_name: discovery-service
    networks:
      - ecommerce-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: krishnakant2001/config-server
    container_name: config-server
    networks:
      - ecommerce-network
    depends_on:
      - discovery-service

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    image: krishnakant2001/inventory-service
    container_name: inventory-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - inventory-db

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: krishnakant2001/order-service
    container_name: order-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - order-db

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: krishnakant2001/api-gateway
    container_name: api-gateway
    networks:
      - ecommerce-network
    depends_on:
      - inventory-service
      - order-service
    ports:
      - "8080:8080"

volumes:
  inventory-db-data:
  order-db-data:

networks:
  ecommerce-network:
